name: Check Plugin Resources Path
on: [push, pull_request, workflow_dispatch]

jobs:
  check-resources:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Run resource check
        run: |
          python3 plugin_path_checker.py "res://addons/konado/" "./addons/konado/"